name: apiverve_botdetector
description: Bot Detector is an API that analyzes user agent strings to identify bots, crawlers, and automated software. Useful for security, analytics, and access control.
version: 1.1.13
homepage: https://apiverve.com/marketplace/botdetector?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/botdetector-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
